name: CI
on:
  workflow_dispatch:
    inputs:
      statement:
        description: 'put some sql here'     
        required: true
        default: 'create table a(x int); select * from a;'
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        PGPASSWORD=postgres psql -h localhost -p ${{ job.services.postgres.ports[5432] }} -U postgres postgres <<EOF
        \x
        ${{ github.event.inputs.statement }}
        EOF
